# Site settings
title: "Bug recreational use"
email: "nicolas@guelpa.me"
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nicolas.guelpa.me" # the base hostname & protocol for your site
domain: "nicolas.guelpa.me"

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
